project:
  output-dir: ./_site/en

book:
  title: "Introduction to databases"
  chapters:
    - index.qmd
    - part: "Database Introduction"
      chapters:
        - course-contents/databases-intro-en.qmd
#        - course-contents/database-ranking-market-share-en.qmd
#        - course-contents/open-source-vs-enterprise-databases-en.qmd
#        - course-contents/which-databases-will-be-covered-en.md 
#        - course-contents/server-installation-en.qmd
        - course-contents/database-playground-en.md
        - course-contents/database-connections-en.qmd
#        - course-contents/example-database-schemas-en.qmd
#        - course-contents/command-line-access-en.qmd
