project:
  type: book
  execute-dir: "project"
  output-dir: ./_site

book:
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  output-file: "databases"
  chapters:
      - index.qmd


profile:
  default: en
  group: 
    - [def,en]



