project:
  output-dir: ./_site/en

book:
  title: "Introduction to databases"
  chapters:
    - index.qmd
    - part: "Database Introduction"
      chapters:
        - course-contents/database-playground-en.md
        - course-contents/database-connections-en.qmd
